name: websocket_ping_validator
description: A dart package to use websockets and check the connection
version: 1.1.4
homepage: https://github.com/Flerma98
repository: https://github.com/Flerma98/dart_websocket_ping_validator
issue_tracker: https://github.com/Flerma98/dart_websocket_ping_validator

environment:
  sdk: '>=2.14.0 <4.0.0'
